# Generated by Django 3.2.6 on 2021-08-21 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('umur', models.IntegerField()),
                ('gender', models.CharField(choices=[('lk', 'Laki-laki'), ('pr', 'Perempuan')], max_length=10)),
                ('foto', models.ImageField(upload_to='chef/')),
            ],
        ),
    ]
