# Generated by Django 3.2.6 on 2021-08-21 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chef',
            name='show',
            field=models.BooleanField(default=True),
        ),
    ]
