# Generated by Django 3.2.6 on 2021-09-26 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0002_chef_show'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('harga', models.FloatField()),
                ('gambar', models.ImageField(upload_to='food/')),
                ('chef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.chef')),
            ],
        ),
    ]
